### PR TITLE
fix(work): unbreak rust-rewrite — missing CardCreated.origin in projection test (merge race #1127×#1137)

### PR DESCRIPTION
**Pull request by joelteply**
rust-rewrite tip fails to compile: `error[E0063]: missing field `origin` in initializer of `event::CardCreated`` at `crates/airc-work/src/projection/tests.rs:1596`.

**Merge race:** #1127 added `CardCreated.origin` + updated all then-existing constructors; #1137's projection test was authored against the pre-#1127 base and added a constructor without `origin`. Git saw no textual conflict, so both passed CI individually — the *combination* doesn't build. This reds `cargo test` + `cargo clippy --all-targets` on every leg and blocks all PRs (incl. #1138).

**Fix:** `origin: None` — the legacy/operator default every other test constructor uses. `cargo check --workspace --all-targets` is green locally.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by joelteply** [comment]
Merging to unblock the base. clippy ✅ ubuntu ✅ fmt ✅ quality ✅ (two full --all-targets compiles confirm the E0063 fix); macos/windows legs are slow/congested infra, not code signals, and `cargo check --workspace --all-targets` is green locally. rust-rewrite is red for every PR until this lands — speed matters here.
